### PR TITLE
Add some function

### PR DESCRIPTION
**Pull request by luantranminh**
complete 'Save as PDF' and 'Change theme'

### CODE REVIEW

**Comment by faraazahmad** [comment]
This is great! But we want the user to change the theme as they require. For that we need a dialog with at least 3 themes built in You can see the material palette at http://materialpalette.com/

**Comment by luantranminh** [comment]
OK, I fixed, it's not a big deal

**Comment by faraazahmad** [comment]
No, my friend :)



The change theme button should open a scrolling dialog box with built-in themes using a material color palette, like so

**Comment by faraazahmad** [comment]
Visit this link for more info
https://material-components-web.appspot.com/dialog.html

**Comment by luantranminh** [comment]
It's kind of fun, huh :)) Sorry, my bad. I'm a freshman. I just learned about js.

**Comment by faraazahmad** [comment]
That's great! It has some tiny issues but let's open some other issues, so that others can benefit too for hacktoberfest

**Pull request merged**
